// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-sphere/sphere-simple-layout/internal/config"
	api2 "github.com/go-sphere/sphere-simple-layout/internal/server/api"
	"github.com/go-sphere/sphere-simple-layout/internal/service/api"
	"github.com/go-sphere/sphere/core/boot"
)

// Injectors from wire.go:

func NewApplication(conf *config.Config) (*boot.Application, error) {
	apiConfig := conf.API
	service := api.NewService()
	web := api2.NewWebServer(apiConfig, service)
	application := newApplication(web)
	return application, nil
}
